### ISSUE TITLE
Recent update to multiskin causing clothing to crash Minetest @ unified_inventory.

### ISSUE THREAD

**Issue by Cat5TV** [stujones11/clothing#2]
Running up to date pull of 3d_armour (with multiskin) + clothing + unified_inventory. Since recent update on multiskin, now Minetest server crashes with:
Undeclared global variable "perplayer_formspec" accessed at mods/clothing/clothing.lua:53

Thanks in advance for fixing this.

**Comment by Cat5TV** [comment]
--Whoops, looks like TenPlus1 posted a split second before me.  :)

**Comment by stujones11** [comment]
No problem, thank you for reporting.
