### ISSUE TITLE
Capes not applying

### ISSUE THREAD

**Issue by ghost** [stujones11/clothing#6]
I just tested using a stock MT/G with `clothing` and `multiskin` mods only, and can not apply capes. 

Edit: A quick look revealed capes with group cape = 1 while detached inv allow_put checks for clothing group only.

**Comment by ghost** [comment]
The following worked:
```diff --git a/init.lua b/init.lua
index 1751291..f5e97d3 100644
--- a/init.lua
+++ b/init.lua
@@ -81,7 +81,8 @@ minetest.register_on_joinplayer(function(player)
                end,
                allow_put = function(inv, listname, index, stack, player)
                        local item = stack:get_name()
-                       if minetest.get_item_group(item, "clothing") > 0 then
+                       if minetest.get_item_group(item, "clothing") > 0 or
+                                       minetest.get_item_group(item, "cape") > 0 then
                                return 1
                        end
                        return 0
```
Is this suitable?

**Comment by stujones11** [comment]
That would work but I think the proper fix would be to give the capes the clothing group also. Thank you for pointing this out.

**Edit:** Actually, it might not be as simple as that, I would also need to change the api slightly for that to work. In the meantime your own patch should be fine.

**Comment by stujones11** [comment]
94e1b9f8ba3acad63c8918273052d8a608078053
